# -----------------------------------------------------------------------------
# Site Navigation (Complete)
# -----------------------------------------------------------------------------

[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "Longform"
  url = "/posts/"
  weight = 20

[[main]]
  name = "Status"
  url = "/kinds/status/"
  weight = 30

[[main]]
  name = "Replies"
  url = "/kinds/reply/"
  weight = 40

[[main]]
  name = "Reposts"
  url = "/kinds/repost/"
  weight = 50

[[main]]
  name = "Likes"
  url = "/kinds/like/"
  weight = 60

[[main]]
  name = "Bookmarks"
  url = "/kinds/bookmark/"
  weight = 70

[[main]]
  name = "Events"
  url = "/kinds/rsvp/"
  weight = 80

[[main]]
  name = "Guestbook"
  url = "/guestbook/"
  weight = 90

[[main]]
  name = "Contact"
  url = "/contact/"
  weight = 100

[[main]]
  name = "Search"
  url = "/search/"
  weight = 110
