[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "Longform"
  url = "/longform/"
  weight = 20

[[main]]
  name = "Status"
  url = "/status/"
  weight = 30

[[main]]
  name = "Replies"
  url = "/replies/"
  weight = 40

[[main]]
  name = "Reposts"
  url = "/reposts/"
  weight = 50

[[main]]
  name = "Likes"
  url = "/likes/"
  weight = 60

[[main]]
  name = "Bookmarks"
  url = "/bookmarks/"
  weight = 70

[[main]]
  name = "Events"
  url = "/events/"
  weight = 80

[[main]]
  name = "Guestbook"
  url = "/guestbook/"
  weight = 90

[[main]]
  name = "Contact"
  url = "/contact/"
  weight = 100

[[main]]
  name = "Search"
  url = "/search/"
  weight = 110
