#!/bin/bash
# ==============================================================================
# SCRIPT: generate_local_wiki.sh
# PURPOSE: Create a comprehensive Local-Only Style Guide.
# STRUCTURE: /content/styleguide/ (Ignored by Git)
# ==============================================================================

GUIDE_ROOT="content/styleguide"

echo "--- Generating Local Style Guide (Wiki) ---"

# 1. UPDATE GITIGNORE
# Ensure this folder never gets committed.
if ! grep -q "content/styleguide/" .gitignore; then
    echo "content/styleguide/" >> .gitignore
    echo "✓ Added styleguide to .gitignore."
fi

# 2. CREATE DIRECTORY STRUCTURE
mkdir -p "$GUIDE_ROOT/design-system"
mkdir -p "$GUIDE_ROOT/archetypes"

# 3. ROOT INDEX
cat <<MD_EOF > "$GUIDE_ROOT/_index.md"
---
title: "Dev Style Guide"
summary: "Internal design system documentation and component tests."
show_webmentions: false
---

## Welcome, Developer.
This section is visible **only** in your local environment. It is excluded from Git.
Use this to test styling changes without creating dummy posts in the main feed.

### 📚 Sections
1. **[Design System](/styleguide/design-system/)**
   Colors, Typography, Forms, and Core Components.
2. **[Archetypes](/styleguide/archetypes/)**
   Live renders of Statuses, Replies, Bookmarks, and more.

---
*Generated by generate_local_wiki.sh*
MD_EOF

# 4. DESIGN SYSTEM (Kitchen Sink)
cat <<MD_EOF > "$GUIDE_ROOT/design-system/_index.md"
---
title: "Design System"
summary: "Visual reference for base styles."
show_webmentions: false
---

## 1. Typography (Typescale)
# Display H1
## Headline H2
### Title H3
#### Title Medium H4
##### Title Small H5
###### Label H6

Standard body text. The quick brown fox jumps over the lazy dog. **Bold text** and *Italic text*.

---

## 2. Interactive Elements
<button class="button-primary">Primary Button</button>
<button class="button-secondary">Secondary Button</button>
<br><br>
<input type="text" placeholder="Text Input (Pill)">

---

## 3. Content Blocks
> **Blockquote:** "Design is intelligence made visible." 
> — *Alina Wheeler*

### Data Table
| ID | Status | Load |
| :--- | :--- | :--- |
| **SYS-01** | Online | 45% |
| **SYS-02** | Offline | 0% |
{caption="System Status"}

---

## 4. Code & Syntax
\`\`\`css
.example-class {
  color: var(--md-sys-color-primary);
  border-radius: 24px;
}
\`\`\`
MD_EOF

# 5. ARCHETYPE EXAMPLES
# This index lists the specific tests.
cat <<MD_EOF > "$GUIDE_ROOT/archetypes/_index.md"
---
title: "Archetype Tests"
summary: "Visual tests for IndieWeb content types."
show_webmentions: false
---

These pages use \`fake_type\` to simulate different content types.

* [Status Update Test](/styleguide/archetypes/test-status/)
* [Reply Test](/styleguide/archetypes/test-reply/)
* [Bookmark Test](/styleguide/archetypes/test-bookmark/)
* [Like Test](/styleguide/archetypes/test-like/)
* [Repost Test](/styleguide/archetypes/test-repost/)
* [RSVP Test](/styleguide/archetypes/test-rsvp/)
MD_EOF

# --- INDIVIDUAL ARCHETYPE PAGES ---

# STATUS
cat <<MD_EOF > "$GUIDE_ROOT/archetypes/test-status.md"
---
title: "Just a quick thought..."
date: 2025-11-27T10:00:00-08:00
fake_type: "status"
summary: "Testing the Status Update styling."
show_webmentions: false
---
This is how a **Status Update** looks. It should have a tinted background and resemble a note card.
MD_EOF

# REPLY
cat <<MD_EOF > "$GUIDE_ROOT/archetypes/test-reply.md"
---
title: "Reply to Post"
date: 2025-11-27T10:05:00-08:00
fake_type: "replies"
reply_to: "https://example.com/original-post"
show_webmentions: false
---
This is a **Reply**. It should have a thick colored border on the left and a visible Context Card above.
MD_EOF

# BOOKMARK
cat <<MD_EOF > "$GUIDE_ROOT/archetypes/test-bookmark.md"
---
title: "Cool Resource: Hugo Docs"
date: 2025-11-27T10:10:00-08:00
fake_type: "bookmarks"
bookmark_of: "https://gohugo.io"
summary: "The official documentation for Hugo."
show_webmentions: false
---
This is a **Bookmark**. It should have a dashed border.
MD_EOF

# LIKE
cat <<MD_EOF > "$GUIDE_ROOT/archetypes/test-like.md"
---
title: "Liked: Some Awesome Article"
date: 2025-11-27T10:15:00-08:00
fake_type: "likes"
like_of: "https://example.com/awesome-article"
show_webmentions: false
---
(Content is usually hidden for Likes). This should look like a small pill.
MD_EOF

# REPOST
cat <<MD_EOF > "$GUIDE_ROOT/archetypes/test-repost.md"
---
title: "Repost: Important Announcement"
date: 2025-11-27T10:20:00-08:00
fake_type: "reposts"
repost_of: "https://example.com/announcement"
show_webmentions: false
---
This is a **Repost**. It should look like a framed container with a watermark icon.
MD_EOF

# RSVP
cat <<MD_EOF > "$GUIDE_ROOT/archetypes/test-rsvp.md"
---
title: "IndieWeb Summit 2025"
date: 2025-11-27T10:25:00-08:00
fake_type: "rsvps"
rsvp: "yes"
reply_to: "https://indieweb.org/2025"
show_webmentions: false
---
I am going to this event! This should look like a ticket stub.
MD_EOF

echo "✓ Style Guide generated in /content/styleguide/"
echo "--- Run 'hugo server' and check the footer for the link! ---"
